baseURL = 'https://georgechirayil.github.io/'
languageCode = 'en-us'
title = 'My Web Site'
copyright = "(c) 2005 - George Chirayil. All rights reserved."
theme = 'ananke'
[menus]
    [[menus.main]]
        name = "Home"
        pageRef = "/"
        weight = 10
    [[menus.main]]
        name = "About"
        pageRef = "/about"
        weight = 30
[outputs]
    home = ["HTML"]
